apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
rules:
  - apiGroups: ["apps"]
    resources:
      - pods
      - deployments
    verbs:
      - get
      - list
      - delete
      - watch
      - create
      - update
      - patch
